-- ==========================================
-- 1. DROP EXISTING TABLES
-- ==========================================
DROP TABLE IF EXISTS AOK CASCADE;
DROP TABLE IF EXISTS EventVendor CASCADE;
DROP TABLE IF EXISTS OrderEvent CASCADE;
DROP TABLE IF EXISTS Vendor CASCADE;
DROP TABLE IF EXISTS Klien CASCADE;
DROP TABLE IF EXISTS Asisten CASCADE;
DROP TABLE IF EXISTS Pemilik CASCADE;

-- ==========================================
-- 2. CREATE TABLES
-- ==========================================

-- Tabel Pemilik
CREATE TABLE Pemilik (
    idPemilik INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nama VARCHAR(50),
    email VARCHAR(100),
    noTelp VARCHAR(25),           -- Kolom noTelp
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    isDeleted BOOLEAN DEFAULT FALSE
);

-- Tabel Asisten
CREATE TABLE Asisten (
    idAsisten INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nama VARCHAR(50),
    alamat VARCHAR(150),
    noTelp VARCHAR(25),
    email VARCHAR(100),
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    isDeleted BOOLEAN DEFAULT FALSE
);

-- Tabel Klien
CREATE TABLE Klien (
    idKlien INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nama VARCHAR(50),
    alamat VARCHAR(150),
    noTelp VARCHAR(25),
    email VARCHAR(100),
    isDeleted BOOLEAN DEFAULT FALSE
);

-- Tabel Vendor
CREATE TABLE Vendor (
    idVendor INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nama VARCHAR(50),
    noTelp VARCHAR(25),
    email VARCHAR(100),
    namaPemilik VARCHAR(50),
    jenisVendor VARCHAR(50),
    harga INT,
    isDeleted BOOLEAN DEFAULT FALSE
);

-- Tabel OrderEvent
CREATE TABLE OrderEvent (
    idOrder INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    budget MONEY,
    jenisEvent VARCHAR(150),
    idEvent INT GENERATED ALWAYS AS (idOrder) STORED UNIQUE,
    nama VARCHAR(50),
    alamat VARCHAR(150),
    tgl DATE,
    jumlahUndangan INT,
    laporan VARCHAR(2000),
    totalHarga MONEY,
    isDeleted BOOLEAN DEFAULT FALSE
);

-- Tabel Relasi Event - Vendor
CREATE TABLE EventVendor (
    idVendor INT,
    idEvent INT,
    FOREIGN KEY (idVendor) REFERENCES Vendor(idVendor),
    FOREIGN KEY (idEvent) REFERENCES OrderEvent(idEvent)
);

-- Tabel Relasi Asisten - Order - Klien
CREATE TABLE AOK (
    idAsisten INT,
    idKlien INT,
    idOrder INT,
    FOREIGN KEY (idAsisten) REFERENCES Asisten(idAsisten),
    FOREIGN KEY (idKlien) REFERENCES Klien(idKlien),
    FOREIGN KEY (idOrder) REFERENCES OrderEvent(idOrder)
);

-- ==========================================
-- 3. INSERT DUMMY DATA LENGKAP
-- ==========================================

-- 1. INSERT PEMILIK
INSERT INTO Pemilik (nama, email, noTelp, username, password, isDeleted) VALUES
('Kapi', 'kapi@eo.com', '08111222333', 'kapi', '{noop}12345', FALSE); -- Password: 12345

-- 2. INSERT ASISTEN
INSERT INTO Asisten (nama, alamat, noTelp, email, username, password, isDeleted) VALUES
('Dina Kusuma', 'Jl. Mawar No. 10', '081234567890', 'dina@eo.com', 'dina', '{noop}12345', FALSE), -- Password: 12345
('Rika Sari', 'Jl. Melati No. 20', '081234567891', 'rika@eo.com', 'rika', '{noop}12345', FALSE), -- Password: 12345
('Andi Pratama', 'Jl. Kenanga No. 30', '081234567892', 'andi@eo.com', 'andi', '{noop}12345', FALSE); -- Password: 12345

-- 3. INSERT KLIEN
INSERT INTO Klien (nama, alamat, noTelp, email, isDeleted) VALUES
('PT Teknologi Maju', 'Gd. Cyber Lt. 5', '021-5559999', 'hr@tekno.com', FALSE),
('Ibu Ratna', 'Menteng Asri', '081987654321', 'ratna@gmail.com', FALSE),
('Bpk. Hartono', 'Pondok Indah', '081122334455', 'hartono@yahoo.com', FALSE);

-- 4. INSERT VENDOR (DATA LENGKAP & BEREAGAM)
INSERT INTO Vendor (nama, noTelp, email, namaPemilik, jenisVendor, harga, isDeleted) VALUES
-- ID 1: Venue
('Grand Ballroom Hotel Santika', '021-5551234', 'ballroom@santika.com', 'Budi Santoso', 'Venue', 50000000, FALSE),
-- ID 2: Kue
('Wombi Cake & Bakery', '081299887766', 'order@wombicake.com', 'Wombi', 'Kue & Dessert', 5000000, FALSE),
-- ID 3: Dekorasi
('Cahaya Dekorasi', '081344556677', 'admin@cahayadekor.com', 'Siti Nurhaliza', 'Dekorasi', 15000000, FALSE),
-- ID 4: Katering
('Rasa Nusantara Catering', '021-7778889', 'info@rasanusantara.com', 'Ahmad Yani', 'Katering', 75000, FALSE),
-- ID 5: Foto
('Lensa Indah Photography', '085611223344', 'contact@lensaindah.com', 'Rudi Hartono', 'Fotografer', 8000000, FALSE),
-- ID 6: Video (Baru)
('Cinematic Wedding', '081855667788', 'hello@cinematic.com', 'Dedi Mizwar', 'Videografer', 12000000, FALSE),
-- ID 7: MUA (Baru)
('Cantik Sempurna MUA', '081233445566', 'booking@cantikmua.com', 'Tasya Farasya', 'MUA', 3500000, FALSE),
-- ID 8: MC (Baru)
('Suara Emas MC', '081944556677', 'mc@suaraemas.com', 'Choky Sitohang', 'MC', 5000000, FALSE),
-- ID 9: Musik (Baru)
('Akustik Harmoni Band', '087788990011', 'band@akustikharmoni.com', 'Kevin Aprilio', 'Musik & Hiburan', 7000000, FALSE),
-- ID 10: Gaun (Baru)
('Royal Wedding Gown', '021-9990001', 'rent@royalgown.com', 'Ivan Gunawan', 'Gaun & Dress', 15000000, FALSE);


-- 5. INSERT ORDER EVENT
INSERT INTO OrderEvent (budget, jenisEvent, nama, alamat, tgl, jumlahUndangan, laporan, totalHarga, isDeleted) VALUES
(200000000, 'Corporate Gathering', 'Anniversary PT Tekno', 'Hotel Santika', '2025-12-10', 100, 'Persiapan 80%', 150000000, FALSE),
(75000000, 'Birthday Party', 'Ultah Anak Ratna', 'Rumah Menteng', '2025-11-20', 50, 'Menunggu konfirmasi katering', 60000000, FALSE),
(500000000, 'Wedding', 'Pernikahan Putri Bpk Hartono', 'Hotel Santika', '2026-01-15', 500, 'Vendor lengkap', 450000000, FALSE);

-- 6. INSERT RELASI (EventVendor)
INSERT INTO EventVendor (idVendor, idEvent) VALUES 
(1, 1), -- Santika untuk PT Tekno
(4, 1), -- Catering Rasa untuk PT Tekno
(5, 1), -- Foto Lensa untuk PT Tekno
(8, 1), -- MC untuk PT Tekno
(2, 2), -- Kue Wombi untuk Ultah
(3, 2), -- Dekorasi Cahaya untuk Ultah
(1, 3), -- Santika untuk Wedding
(3, 3), -- Dekorasi untuk Wedding
(4, 3), -- Catering untuk Wedding
(6, 3), -- Video untuk Wedding
(7, 3), -- MUA untuk Wedding
(9, 3), -- Band untuk Wedding
(10, 3); -- Gaun untuk Wedding

-- 7. INSERT RELASI (AOK)
INSERT INTO AOK (idAsisten, idKlien, idOrder) VALUES 
(1, 1, 1), 
(2, 2, 2), 
(3, 3, 3);